name: Terraform plan

on:
  pull_request

jobs:
  build:
    steps:
    - uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7

    - name: init
      run: terraform init

    - name: plan
      run: terraform plan -out=tfplan

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tfplan
        path: ./tfplan
        
        retention-days: 5
